create table if not exists public.accounting_entries (
 id bigint generated by default as identity primary key,
 date date not null default current_date,
 type text not null check (type in ('income','expense')),
 party text,
 amount numeric(14,2) not null check (amount > 0),
 narration text,
 created_at timestamptz not null default now()
);
alter table public.accounting_entries enable row level security;
-- For a private single-user prototype, keep the table inaccessible from the browser until Auth is added.
-- Once Supabase Auth is enabled, add policies tied to auth.uid() and a user_id column.
